---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-ledfx"
  ADDON_SLUG: "ledfx"
  ADDON_TARGET: "ledfx"

  ADDON_AMD64_BASE: "hassioaddons/base-python-amd64:5.2.0"
  ADDON_ARMHF_BASE: "hassioaddons/base-python-armhf:5.2.0"
  ADDON_ARMV7_BASE: "hassioaddons/base-python-armv7:5.2.0"
  ADDON_AARCH64_BASE: "hassioaddons/base-python-aarch64:5.2.0"
  ADDON_I386_BASE: "hassioaddons/base-python-i386:5.2.0"
